stages:
  - build
  - deploy

# dist:
#   stage: dist
#   image: python:3.10-alpine
#   artifacts:
#     paths:
#       - build/dist/
#   before_script:
#     - apk add --no-cache git
#     - pip install pyyaml
#   script:
#     - python build/docs.py
#   only:
#     refs:
#       - master

build_and_publish:
  stage: build
  image: quay.io/buildah/stable
  variables:
    STORAGE_DRIVER: vfs
    BUILDAH_FORMAT: docker
    CONTAINER_IMAGE: $CI_REGISTRY_IMAGE
  before_script:
    - export REGISTRY_AUTH_FILE=$HOME/auth.json
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - >-
        buildah build
        -t $CONTAINER_IMAGE:$CI_COMMIT_SHORT_SHA
        -t $CONTAINER_IMAGE:latest
    - buildah push $CONTAINER_IMAGE:$CI_COMMIT_SHORT_SHA
    - buildah push $CONTAINER_IMAGE:latest
  only:
    refs:
      - master

deploy:
  stage: deploy
  image: alpine/helm:latest
  variables:
    KUBECONFIG: .kube_config.yml
  script:
    - echo $KUBECONF | base64 -d > .kube_config.yml
    - helm repo add gi0baro https://gi0baro.github.io/helm-charts
    - >-
        helm upgrade --install website
        --atomic
        --namespace emmett-sh
        --values helm/values.yaml
        --set-string image.tag=$CI_COMMIT_SHORT_SHA
        --set-string secrets.sentry_dsn=$K8S_ENV_SENTRY_DSN
        gi0baro/generic
  environment:
    name: production
    url: https://emmett.sh
  only:
    refs:
      - master
