[tool.poetry]
name = "emmett-website"
version = "0.1.0"
description = ""
authors = ["Giovanni Barillari <giovanni.barillari@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
emmett = "2.0.0b1"
emmett-haml = { git = "https://github.com/gi0baro/emmett-haml.git", rev = "09d1ddd" }
markdown2 = "~2.3.8"
pygments = "~2.6.1"

[tool.poetry.dev-dependencies]
pylint = "^2.4.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
