[project]
name = "emmett-website"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = "~=3.10.0"

dependencies = [
    "emmett~=2.5.2",
    "emmett-haml~=1.0",
    "emmett-sentry~=0.6.0",
    "markdown2~=2.3.8",
    "pygments~=2.6.1",
]
