[project]
name = "emmett-website"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = "~=3.13.0"

dependencies = [
    "emmett[rloop]~=2.7.0",
    "emmett-haml~=1.0",
    "emmett-sentry~=0.8.2",
    "markdown2~=2.3.8",
    "pygments~=2.6.1",
]
