nameOverride: emmett-website

image:
  repository: cr.amira.io/emmett/website

resources:
  limits:
    memory: 160Mi
  requests:
    cpu: 20m
    memory: 80Mi

replicas: 2

probes:
  liveness:
    enabled: true
    path: /_health
    initialDelaySeconds: 3
  readiness:
    enabled: true
    path: /_health
    initialDelaySeconds: 3

ingress:
  enabled: true
  className: nginx

  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

  hosts:
    - host: emmett.sh
      paths:
        - /
  tls:
    - hosts:
        - emmett.sh
      secretName: tls-emmett.sh

envValueFrom:
  PRIVATE_HOSTNAME:
    fieldRef:
      fieldPath: status.podIP
